version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_GRAPHQL_URI=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
